### ISSUE TITLE
Safari Technology

### ISSUE THREAD

**Issue by phil-o-man** [phallstrom/SafariFontScope#4]
Thanks for this useful plugin. I recently downloaded Safari Technology Preview and the plugin does not seem to work. I hope you will support Safari Technology in your future version. Thanks and best wishes

**Comment by phallstrom** [comment]
Glad you like it! I'm not sure when I'll get around to it. I need to jump through the hoops of signing up for the Apple Dev program and doing whatever updates are necessary.  One day.... :)

**Comment by sfhosley** [comment]
It's worked in Safari Technology Preview for me since Day 1.

<img width="570" alt="fontscope" src="https://cloud.githubusercontent.com/assets/5246930/16200630/b9c42ab0-36d3-11e6-836b-b9bed8623120.png">
