### ISSUE TITLE
macOS Mojave

### ISSUE THREAD

**Issue by elemis** [phallstrom/SafariFontScope#7]
Are you planning to add this extension to Mac App Store (Safari Extensions Gallery)? Please do. Apparently it is no longer possible to add extensions to Safari from outside :(

**Comment by phallstrom** [comment]
@elemis I would like to, but it might take me awhile to get to.  :sorry:

**Comment by phallstrom** [comment]
@elemis I've submitted it. Now we wait. I don't have Mojave installed, but maybe you can install it now that it's signed?  https://github.com/phallstrom/SafariFontScope/raw/master/FontScope.safariextz

Let me know.

**Comment by elemis** [comment]
@phallstrom thank you. I'm still unable to install it though. I get the following error:
<img width="413" alt="screen shot 2018-08-02 at 10 35 51" src="https://user-images.githubusercontent.com/608547/43569374-ef670c3c-963f-11e8-8508-32c439253e31.png">

**Comment by phallstrom** [comment]
@elemis Well, looks like they approved it.  Can you try installing it and if it works let me know and I'll update the README here to point to that.

https://safari-extensions.apple.com/details/?id=com.pjkh.fontscope-B5Z467B8T6

**Comment by charlenejackie** [comment]
@phallstrom it works now. Thank you very much!
